name: annotation-renderer
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - opencv>=4.8.0
  - ffmpeg
  - pip:
    - nats-py>=2.6.0
    - pyyaml>=6.0.1
    - numpy>=1.24.0
    - fastapi>=0.104.0
    - uvicorn[standard]>=0.24.0
    - boto3>=1.34.0

