name: training-service
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - nats-py>=2.6.0
    - pyyaml>=6.0.1
    - numpy>=1.24.0
    - pandas>=2.0.0
    - catboost>=1.2.0
    - xgboost>=2.0.0
    - lightgbm>=4.0.0
    - scikit-learn>=1.3.0
    - joblib>=1.3.0

