name: tleap-pipeline
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - opencv>=4.8.0
  - pip:
    - torch>=2.0.0
    - nats-py>=2.6.0
    - pyyaml>=6.0.1
    - numpy>=1.24.0
    - opencv-python>=4.8.0


